use crate::type_map::{csharp_default_value, csharp_type};
use heck::ToPascalCase;
use skif_codegen::naming::to_csharp_name;
use skif_core::backend::{Backend, Capabilities, GeneratedFile};
use skif_core::config::{Language, SkifConfig, resolve_output_dir};
use skif_core::ir::{ApiSurface, EnumDef, FunctionDef, MethodDef, TypeDef, TypeRef};
use std::path::PathBuf;

pub struct CsharpBackend;

impl CsharpBackend {
    /// Get the library name for P/Invoke.
    fn lib_name(prefix: &str) -> String {
        // Use just the prefix if it looks like a lib name, otherwise append _ffi
        if prefix.ends_with("_ffi") || prefix == "ffi" {
            prefix.to_string()
        } else {
            format!("{}_ffi", prefix)
        }
    }
}

impl Backend for CsharpBackend {
    fn name(&self) -> &str {
        "csharp"
    }

    fn language(&self) -> Language {
        Language::Csharp
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            ..Capabilities::default()
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &SkifConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let namespace = config.csharp_namespace();
        let prefix = config.ffi_prefix();
        let lib_name = Self::lib_name(&prefix);

        let output_dir = resolve_output_dir(
            config.output.csharp.as_ref(),
            &config.crate_config.name,
            "packages/csharp/",
        );

        let base_path = PathBuf::from(&output_dir).join(namespace.replace('.', "/"));

        let mut files = Vec::new();

        // 1. Generate NativeMethods.cs
        files.push(GeneratedFile {
            path: base_path.join("NativeMethods.cs"),
            content: gen_native_methods(api, &namespace, &lib_name, &prefix),
            generated_header: true,
        });

        // 2. Generate exception class
        let exception_class_name = format!("{}Exception", api.crate_name.to_pascal_case());
        files.push(GeneratedFile {
            path: base_path.join(format!("{}.cs", exception_class_name)),
            content: gen_exception_class(&namespace, &exception_class_name),
            generated_header: true,
        });

        // 3. Generate main wrapper class
        let wrapper_class_name = api.crate_name.to_pascal_case();
        files.push(GeneratedFile {
            path: base_path.join(format!("{}.cs", wrapper_class_name)),
            content: gen_wrapper_class(api, &namespace, &wrapper_class_name, &exception_class_name, &prefix),
            generated_header: true,
        });

        // 4. Generate record types (structs)
        for typ in &api.types {
            if !typ.is_opaque {
                let type_filename = typ.name.to_pascal_case();
                files.push(GeneratedFile {
                    path: base_path.join(format!("{}.cs", type_filename)),
                    content: gen_record_type(typ, &namespace),
                    generated_header: true,
                });
            }
        }

        // 5. Generate enums
        for enum_def in &api.enums {
            let enum_filename = enum_def.name.to_pascal_case();
            files.push(GeneratedFile {
                path: base_path.join(format!("{}.cs", enum_filename)),
                content: gen_enum(enum_def, &namespace),
                generated_header: true,
            });
        }

        Ok(files)
    }
}

// ---------------------------------------------------------------------------
// Code generation functions
// ---------------------------------------------------------------------------

fn gen_native_methods(api: &ApiSurface, namespace: &str, lib_name: &str, prefix: &str) -> String {
    let mut out = String::from(
        "// This file is auto-generated by skif. DO NOT EDIT.\n\
         using System.Runtime.InteropServices;\n\n",
    );

    out.push_str(&format!("namespace {};\n\n", namespace));

    out.push_str("internal static partial class NativeMethods\n{\n");
    out.push_str(&format!("    private const string LibName = \"{}\";\n\n", lib_name));

    // Generate P/Invoke declarations for functions
    for func in &api.functions {
        let c_func_name = format!("{}_{}", prefix, func.name.to_lowercase());
        out.push_str(&gen_pinvoke_for_func(&c_func_name, func));
    }

    // Generate P/Invoke declarations for type methods
    for typ in &api.types {
        for method in &typ.methods {
            let c_method_name = format!("{}_{}", prefix, method.name.to_lowercase());
            out.push_str(&gen_pinvoke_for_method(&c_method_name, method));
        }
    }

    // Add error handling functions
    out.push_str("    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n");
    out.push_str(&format!(
        "    internal static extern int {}_last_error_code();\n\n",
        prefix
    ));

    out.push_str("    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n");
    out.push_str(&format!(
        "    internal static extern IntPtr {}_last_error_context();\n\n",
        prefix
    ));

    out.push_str("    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n");
    out.push_str(&format!(
        "    internal static extern void {}_free_string(IntPtr ptr);\n",
        prefix
    ));

    out.push_str("}\n");

    out
}

fn gen_pinvoke_for_func(c_name: &str, func: &FunctionDef) -> String {
    let mut out = String::from("    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n");
    out.push_str("    internal static extern ");

    // Return type
    if func.return_type == TypeRef::Unit {
        out.push_str("void");
    } else {
        out.push_str("IntPtr");
    }

    out.push_str(&format!(" {}(", c_name));

    if func.params.is_empty() {
        out.push_str(");\n\n");
    } else {
        out.push('\n');
        for (i, param) in func.params.iter().enumerate() {
            out.push_str("        ");
            if param.ty == TypeRef::String {
                out.push_str("[MarshalAs(UnmanagedType.LPStr)] ");
            }
            out.push_str(&format!("{} {}", csharp_type(&param.ty), param.name));

            if i < func.params.len() - 1 {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("    );\n\n");
    }

    out
}

fn gen_pinvoke_for_method(c_name: &str, method: &MethodDef) -> String {
    let mut out = String::from("    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n");
    out.push_str("    internal static extern ");

    // Return type
    if method.return_type == TypeRef::Unit {
        out.push_str("void");
    } else {
        out.push_str("IntPtr");
    }

    out.push_str(&format!(" {}(", c_name));

    if method.params.is_empty() {
        out.push_str(");\n\n");
    } else {
        out.push('\n');
        for (i, param) in method.params.iter().enumerate() {
            out.push_str("        ");
            if param.ty == TypeRef::String {
                out.push_str("[MarshalAs(UnmanagedType.LPStr)] ");
            }
            out.push_str(&format!("{} {}", csharp_type(&param.ty), param.name));

            if i < method.params.len() - 1 {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("    );\n\n");
    }

    out
}

fn gen_exception_class(namespace: &str, class_name: &str) -> String {
    let mut out = String::from(
        "// This file is auto-generated by skif. DO NOT EDIT.\n\
         using System;\n\n",
    );

    out.push_str(&format!("namespace {};\n\n", namespace));

    out.push_str(&format!("public class {} : Exception\n", class_name));
    out.push_str("{\n");
    out.push_str("    public int Code { get; }\n\n");
    out.push_str(&format!(
        "    public {}(int code, string message) : base(message)\n",
        class_name
    ));
    out.push_str("    {\n");
    out.push_str("        Code = code;\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

fn gen_wrapper_class(
    api: &ApiSurface,
    namespace: &str,
    class_name: &str,
    exception_name: &str,
    prefix: &str,
) -> String {
    let mut out = String::from(
        "// This file is auto-generated by skif. DO NOT EDIT.\n\
         using System;\n\
         using System.Collections.Generic;\n\
         using System.Runtime.InteropServices;\n\
         using System.Text.Json;\n\
         using System.Text.Json.Serialization;\n\
         using System.Threading.Tasks;\n\n",
    );

    out.push_str(&format!("namespace {};\n\n", namespace));

    out.push_str(&format!("public static class {}\n", class_name));
    out.push_str("{\n");

    // Generate wrapper methods for functions
    for func in &api.functions {
        out.push_str(&gen_wrapper_function(func, exception_name, prefix));
    }

    // Generate wrapper methods for type methods
    for typ in &api.types {
        if !typ.is_opaque {
            for method in &typ.methods {
                out.push_str(&gen_wrapper_method(method, exception_name, prefix));
            }
        }
    }

    // Add error handling helper
    out.push_str("    private static ");
    out.push_str(&format!("{} GetLastError()\n", exception_name));
    out.push_str("    {\n");
    out.push_str(&format!(
        "        var code = NativeMethods.{}_last_error_code();\n",
        prefix
    ));
    out.push_str(&format!(
        "        var ctxPtr = NativeMethods.{}_last_error_context();\n",
        prefix
    ));
    out.push_str("        var message = Marshal.PtrToStringAnsi(ctxPtr) ?? \"Unknown error\";\n");
    out.push_str(&format!("        return new {}(code, message);\n", exception_name));
    out.push_str("    }\n");

    out.push_str("}\n");

    out
}

fn gen_wrapper_function(func: &FunctionDef, _exception_name: &str, prefix: &str) -> String {
    let mut out = String::with_capacity(1024);

    out.push_str("    public static ");

    // Return type
    if func.return_type == TypeRef::Unit {
        out.push_str("void");
    } else {
        out.push_str(&csharp_type(&func.return_type));
    }

    out.push_str(&format!(" {}", to_csharp_name(&func.name)));
    out.push('(');

    // Parameters
    for (i, param) in func.params.iter().enumerate() {
        if param.optional {
            out.push_str(&format!("{}? {}", csharp_type(&param.ty), param.name));
        } else {
            out.push_str(&format!("{} {}", csharp_type(&param.ty), param.name));
        }

        if i < func.params.len() - 1 {
            out.push_str(", ");
        }
    }

    out.push_str(")\n    {\n");

    // Method body - simple delegation to native method
    let c_func_name = format!("{}_{}", prefix, func.name.to_lowercase());

    if func.return_type != TypeRef::Unit {
        out.push_str("        var result = ");
    } else {
        out.push_str("        ");
    }

    out.push_str(&format!("NativeMethods.{}(", c_func_name));

    if func.params.is_empty() {
        out.push_str(");\n");
    } else {
        out.push('\n');
        for (i, param) in func.params.iter().enumerate() {
            out.push_str(&format!("            {}", param.name));
            if i < func.params.len() - 1 {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("        );\n");
    }

    if func.return_type != TypeRef::Unit {
        out.push_str("        return result;\n");
    }

    out.push_str("    }\n\n");

    out
}

fn gen_wrapper_method(method: &MethodDef, _exception_name: &str, prefix: &str) -> String {
    let mut out = String::with_capacity(1024);

    out.push_str("    public ");

    if method.is_static {
        out.push_str("static ");
    }

    // Return type
    if method.return_type == TypeRef::Unit {
        out.push_str("void");
    } else {
        out.push_str(&csharp_type(&method.return_type));
    }

    out.push_str(&format!(" {}", to_csharp_name(&method.name)));
    out.push('(');

    // Parameters
    for (i, param) in method.params.iter().enumerate() {
        if param.optional {
            out.push_str(&format!("{}? {}", csharp_type(&param.ty), param.name));
        } else {
            out.push_str(&format!("{} {}", csharp_type(&param.ty), param.name));
        }

        if i < method.params.len() - 1 {
            out.push_str(", ");
        }
    }

    out.push_str(")\n    {\n");

    // Method body - simple delegation to native method
    let c_method_name = format!("{}_{}", prefix, method.name.to_lowercase());

    if method.return_type != TypeRef::Unit {
        out.push_str("        var result = ");
    } else {
        out.push_str("        ");
    }

    out.push_str(&format!("NativeMethods.{}(", c_method_name));

    if method.params.is_empty() {
        out.push_str(");\n");
    } else {
        out.push('\n');
        for (i, param) in method.params.iter().enumerate() {
            out.push_str(&format!("            {}", param.name));
            if i < method.params.len() - 1 {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("        );\n");
    }

    if method.return_type != TypeRef::Unit {
        out.push_str("        return result;\n");
    }

    out.push_str("    }\n\n");

    out
}

fn gen_record_type(typ: &TypeDef, namespace: &str) -> String {
    let mut out = String::from(
        "// This file is auto-generated by skif. DO NOT EDIT.\n\
         using System;\n\
         using System.Collections.Generic;\n\
         using System.Text.Json.Serialization;\n\n",
    );

    out.push_str(&format!("namespace {};\n\n", namespace));

    // Generate doc comment if available
    if !typ.doc.is_empty() {
        out.push_str("/// <summary>\n");
        for line in typ.doc.lines() {
            out.push_str(&format!("/// {}\n", line));
        }
        out.push_str("/// </summary>\n");
    }

    out.push_str(&format!("public record {}(\n", typ.name.to_pascal_case()));

    // Record parameters
    for (i, field) in typ.fields.iter().enumerate() {
        let field_type = if field.optional {
            format!("{}?", csharp_type(&field.ty))
        } else {
            csharp_type(&field.ty).to_string()
        };

        out.push_str(&format!("    {} {}", field_type, to_csharp_name(&field.name)));

        if let Some(default) = &field.default {
            out.push_str(&format!(" = {}", default));
        } else if field.optional {
            out.push_str(&format!(" = {}", csharp_default_value(&field.ty)));
        }

        if i < typ.fields.len() - 1 {
            out.push(',');
        }
        out.push('\n');
    }

    out.push_str(");\n");

    out
}

fn gen_enum(enum_def: &EnumDef, namespace: &str) -> String {
    let mut out = String::from("// This file is auto-generated by skif. DO NOT EDIT.\n\n");

    out.push_str(&format!("namespace {};\n\n", namespace));

    // Generate doc comment if available
    if !enum_def.doc.is_empty() {
        out.push_str("/// <summary>\n");
        for line in enum_def.doc.lines() {
            out.push_str(&format!("/// {}\n", line));
        }
        out.push_str("/// </summary>\n");
    }

    out.push_str(&format!("public enum {}\n", enum_def.name.to_pascal_case()));
    out.push_str("{\n");

    // Enum variants
    for variant in &enum_def.variants {
        if !variant.doc.is_empty() {
            out.push_str("    /// <summary>\n");
            for line in variant.doc.lines() {
                out.push_str(&format!("    /// {}\n", line));
            }
            out.push_str("    /// </summary>\n");
        }

        out.push_str(&format!("    {},\n", variant.name.to_pascal_case()));
    }

    out.push_str("}\n");

    out
}
