use crate::type_map::{java_boxed_type, java_ffi_type, java_type};
use skif_codegen::naming::{to_class_name, to_java_name};
use skif_core::backend::{Backend, Capabilities, GeneratedFile};
use skif_core::config::{Language, SkifConfig, resolve_output_dir};
use skif_core::ir::{ApiSurface, EnumDef, FunctionDef, TypeDef, TypeRef};
use std::fmt::Write;
use std::path::PathBuf;

pub struct JavaBackend;

impl JavaBackend {
    /// Convert crate name to main class name (PascalCase).
    fn resolve_main_class(api: &ApiSurface) -> String {
        to_class_name(&api.crate_name.replace('-', "_"))
    }
}

impl Backend for JavaBackend {
    fn name(&self) -> &str {
        "java"
    }

    fn language(&self) -> Language {
        Language::Java
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            ..Capabilities::default()
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &SkifConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let package = config.java_package();
        let prefix = config.ffi_prefix();
        let main_class = Self::resolve_main_class(api);
        let package_path = package.replace('.', "/");

        let output_dir = resolve_output_dir(
            config.output.java.as_ref(),
            &config.crate_config.name,
            "packages/java/src/main/java/",
        );

        let base_path = PathBuf::from(&output_dir).join(&package_path);

        let mut files = Vec::new();

        // 1. NativeLib.java - FFI method handles
        files.push(GeneratedFile {
            path: base_path.join("NativeLib.java"),
            content: gen_native_lib(api, config, &package, &prefix),
            generated_header: true,
        });

        // 2. Main wrapper class
        files.push(GeneratedFile {
            path: base_path.join(format!("{}.java", main_class)),
            content: gen_main_class(api, config, &package, &main_class, &prefix),
            generated_header: true,
        });

        // 3. Exception class
        files.push(GeneratedFile {
            path: base_path.join(format!("{}Exception.java", main_class)),
            content: gen_exception_class(&package, &main_class),
            generated_header: true,
        });

        // 4. Record types
        for typ in &api.types {
            if !typ.is_opaque && !typ.fields.is_empty() {
                files.push(GeneratedFile {
                    path: base_path.join(format!("{}.java", typ.name)),
                    content: gen_record_type(&package, typ),
                    generated_header: true,
                });
            }
        }

        // 5. Enums
        for enum_def in &api.enums {
            files.push(GeneratedFile {
                path: base_path.join(format!("{}.java", enum_def.name)),
                content: gen_enum_class(&package, enum_def),
                generated_header: true,
            });
        }

        Ok(files)
    }
}

// ---------------------------------------------------------------------------
// NativeLib.java - FFI method handles
// ---------------------------------------------------------------------------

fn gen_native_lib(api: &ApiSurface, _config: &SkifConfig, package: &str, prefix: &str) -> String {
    let mut out = String::with_capacity(2048);

    writeln!(out, "// DO NOT EDIT - auto-generated by skif").unwrap();
    writeln!(out, "package {};", package).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import java.lang.foreign.*;").unwrap();
    writeln!(out, "import java.lang.invoke.MethodHandle;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "final class NativeLib {{").unwrap();
    writeln!(out, "    private static final Linker LINKER = Linker.nativeLinker();").unwrap();
    writeln!(out, "    private static final SymbolLookup LIB;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    static {{").unwrap();
    writeln!(out, "        System.loadLibrary(\"{}\");", prefix).unwrap();
    writeln!(out, "        LIB = SymbolLookup.loaderLookup();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // Generate method handles for free functions
    for func in &api.functions {
        if !func.is_async {
            let ffi_name = format!("{}_{}", prefix, func.name.to_lowercase());
            let return_layout = gen_ffi_layout(&func.return_type);
            let param_layouts: Vec<String> = func.params.iter().map(|p| gen_ffi_layout(&p.ty)).collect();

            let layout_str = if param_layouts.is_empty() {
                format!("FunctionDescriptor.of({})", return_layout)
            } else {
                format!("FunctionDescriptor.of({}, {})", return_layout, param_layouts.join(", "))
            };

            let handle_name = format!("{}_{}", prefix.to_uppercase(), func.name.to_uppercase());

            writeln!(
                out,
                "    static final MethodHandle {} = LINKER.downcallHandle(",
                handle_name
            )
            .unwrap();
            writeln!(out, "        LIB.find(\"{}\").orElseThrow(),", ffi_name).unwrap();
            writeln!(out, "        {}", layout_str).unwrap();
            writeln!(out, "    );").unwrap();
        }
    }

    // Error handling
    if !api.errors.is_empty() {
        let error_name = &api.errors[0].name;
        let handle_name = format!("{}_GET_{}_MESSAGE", prefix.to_uppercase(), error_name.to_uppercase());
        writeln!(
            out,
            "    static final MethodHandle {} = LINKER.downcallHandle(",
            handle_name
        )
        .unwrap();
        writeln!(
            out,
            "        LIB.find(\"{}_get_{}_message\").orElseThrow(),",
            prefix,
            error_name.to_lowercase()
        )
        .unwrap();
        writeln!(out, "        FunctionDescriptor.of(ValueLayout.ADDRESS)").unwrap();
        writeln!(out, "    );").unwrap();
    }

    writeln!(out, "}}").unwrap();

    out
}

// ---------------------------------------------------------------------------
// Main wrapper class
// ---------------------------------------------------------------------------

fn gen_main_class(api: &ApiSurface, _config: &SkifConfig, package: &str, class_name: &str, prefix: &str) -> String {
    let mut out = String::with_capacity(4096);

    writeln!(out, "// DO NOT EDIT - auto-generated by skif").unwrap();
    writeln!(out, "package {};", package).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import java.lang.foreign.*;").unwrap();
    writeln!(out, "import java.util.*;").unwrap();
    writeln!(out, "import java.util.concurrent.CompletableFuture;").unwrap();
    writeln!(out, "import java.util.concurrent.CompletionException;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "public final class {} {{", class_name).unwrap();
    writeln!(out, "    private {}() {{}}", class_name).unwrap();
    writeln!(out).unwrap();

    // Generate static methods for free functions
    for func in &api.functions {
        // Always generate sync method
        gen_sync_function_method(&mut out, func, prefix, class_name);
        writeln!(out).unwrap();

        // Also generate async wrapper if marked as async
        if func.is_async {
            gen_async_wrapper_method(&mut out, func);
            writeln!(out).unwrap();
        }
    }

    // Add helper methods
    gen_helper_methods(&mut out);

    writeln!(out, "}}").unwrap();

    out
}

fn gen_sync_function_method(out: &mut String, func: &FunctionDef, prefix: &str, class_name: &str) {
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| {
            let ptype = java_type(&p.ty);
            format!("{} {}", ptype, p.name)
        })
        .collect();

    let return_type = java_type(&func.return_type);

    writeln!(
        out,
        "    public static {} {}({}) throws {}Exception {{",
        return_type,
        to_java_name(&func.name),
        params.join(", "),
        class_name
    )
    .unwrap();

    writeln!(out, "        try (var arena = Arena.ofConfined()) {{").unwrap();

    // Marshal parameters
    for param in &func.params {
        marshal_param_to_ffi(out, &param.name, &param.ty);
    }

    // Call FFI
    let ffi_handle = format!("NativeLib.{}_{}", prefix.to_uppercase(), func.name.to_uppercase());

    let call_args: Vec<String> = func.params.iter().map(|p| ffi_param_name(&p.name, &p.ty)).collect();

    if matches!(func.return_type, TypeRef::Unit) {
        writeln!(out, "            {}.invoke({});", ffi_handle, call_args.join(", ")).unwrap();
        writeln!(out, "        }} catch (Throwable t) {{").unwrap();
        writeln!(
            out,
            "            throw new {}Exception(\"FFI call failed\", t);",
            class_name
        )
        .unwrap();
        writeln!(out, "        }}").unwrap();
    } else {
        writeln!(
            out,
            "            var result = {}.invoke({});",
            ffi_handle,
            call_args.join(", ")
        )
        .unwrap();
        writeln!(out, "            return ({}) result;", return_type).unwrap();
        writeln!(out, "        }} catch (Throwable t) {{").unwrap();
        writeln!(
            out,
            "            throw new {}Exception(\"FFI call failed\", t);",
            class_name
        )
        .unwrap();
        writeln!(out, "        }}").unwrap();
    }

    writeln!(out, "    }}").unwrap();
}

fn gen_async_wrapper_method(out: &mut String, func: &FunctionDef) {
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| {
            let ptype = java_type(&p.ty);
            format!("{} {}", ptype, p.name)
        })
        .collect();

    let return_type = match &func.return_type {
        TypeRef::Unit => "Void".to_string(),
        other => java_boxed_type(other).to_string(),
    };

    let sync_method_name = to_java_name(&func.name);
    let async_method_name = format!("{}Async", sync_method_name);
    let param_names: Vec<String> = func.params.iter().map(|p| p.name.clone()).collect();

    writeln!(
        out,
        "    public static CompletableFuture<{}> {}({}) {{",
        return_type,
        async_method_name,
        params.join(", ")
    )
    .unwrap();
    writeln!(out, "        return CompletableFuture.supplyAsync(() -> {{").unwrap();
    writeln!(out, "            try {{").unwrap();
    writeln!(
        out,
        "                return {}({});",
        sync_method_name,
        param_names.join(", ")
    )
    .unwrap();
    writeln!(out, "            }} catch (Exception e) {{").unwrap();
    writeln!(out, "                throw new CompletionException(e);").unwrap();
    writeln!(out, "            }}").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "    }}").unwrap();
}

// ---------------------------------------------------------------------------
// Exception class
// ---------------------------------------------------------------------------

fn gen_exception_class(package: &str, class_name: &str) -> String {
    let mut out = String::with_capacity(512);

    writeln!(out, "// DO NOT EDIT - auto-generated by skif").unwrap();
    writeln!(out, "package {};", package).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "public class {}Exception extends Exception {{", class_name).unwrap();
    writeln!(out, "    private final int code;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    public {}Exception(int code, String message) {{", class_name).unwrap();
    writeln!(out, "        super(message);").unwrap();
    writeln!(out, "        this.code = code;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "    public {}Exception(String message, Throwable cause) {{",
        class_name
    )
    .unwrap();
    writeln!(out, "        super(message, cause);").unwrap();
    writeln!(out, "        this.code = -1;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    public int getCode() {{").unwrap();
    writeln!(out, "        return code;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    out
}

// ---------------------------------------------------------------------------
// Record types (Java records)
// ---------------------------------------------------------------------------

fn gen_record_type(package: &str, typ: &TypeDef) -> String {
    let mut out = String::with_capacity(1024);

    writeln!(out, "// DO NOT EDIT - auto-generated by skif").unwrap();
    writeln!(out, "package {};", package).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import java.util.*;").unwrap();
    writeln!(out).unwrap();

    let field_list: Vec<String> = typ
        .fields
        .iter()
        .map(|f| {
            let ftype = if f.optional {
                format!("Optional<{}>", java_boxed_type(&f.ty))
            } else {
                java_type(&f.ty).to_string()
            };
            format!("{} {}", ftype, to_java_name(&f.name))
        })
        .collect();

    writeln!(out, "public record {}({}) {{}}", typ.name, field_list.join(", ")).unwrap();

    out
}

// ---------------------------------------------------------------------------
// Enum classes
// ---------------------------------------------------------------------------

fn gen_enum_class(package: &str, enum_def: &EnumDef) -> String {
    let mut out = String::with_capacity(1024);

    writeln!(out, "// DO NOT EDIT - auto-generated by skif").unwrap();
    writeln!(out, "package {};", package).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "public enum {} {{", enum_def.name).unwrap();

    for (i, variant) in enum_def.variants.iter().enumerate() {
        let comma = if i < enum_def.variants.len() - 1 { "," } else { ";" };
        writeln!(out, "    {}{}", variant.name, comma).unwrap();
    }

    writeln!(out, "}}").unwrap();

    out
}

// ---------------------------------------------------------------------------
// Helper functions for FFI marshalling
// ---------------------------------------------------------------------------

fn gen_ffi_layout(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(prim) => java_ffi_type(prim).to_string(),
        TypeRef::String | TypeRef::Path | TypeRef::Json => "ValueLayout.ADDRESS".to_string(),
        TypeRef::Bytes => "ValueLayout.ADDRESS".to_string(),
        TypeRef::Optional(inner) => gen_ffi_layout(inner),
        TypeRef::Vec(_) => "ValueLayout.ADDRESS".to_string(),
        TypeRef::Map(_, _) => "ValueLayout.ADDRESS".to_string(),
        TypeRef::Named(_) => "ValueLayout.ADDRESS".to_string(),
        TypeRef::Unit => "".to_string(),
    }
}

fn marshal_param_to_ffi(out: &mut String, name: &str, ty: &TypeRef) {
    match ty {
        TypeRef::String | TypeRef::Path | TypeRef::Json => {
            let cname = "c".to_string() + name;
            writeln!(out, "            var {} = arena.allocateFrom({});", cname, name).unwrap();
        }
        TypeRef::Optional(inner) => {
            // For optional types, marshal the inner type if not null
            if matches!(inner.as_ref(), TypeRef::String | TypeRef::Path | TypeRef::Json) {
                let cname = "c".to_string() + name;
                writeln!(
                    out,
                    "            var {} = {} != null ? arena.allocateFrom({}) : MemorySegment.NULL;",
                    cname, name, name
                )
                .unwrap();
            }
        }
        _ => {
            // Primitives and others pass through directly
        }
    }
}

fn ffi_param_name(name: &str, ty: &TypeRef) -> String {
    match ty {
        TypeRef::String | TypeRef::Path | TypeRef::Json => "c".to_string() + name,
        TypeRef::Optional(inner) => {
            if matches!(inner.as_ref(), TypeRef::String | TypeRef::Path | TypeRef::Json) {
                "c".to_string() + name
            } else {
                name.to_string()
            }
        }
        _ => name.to_string(),
    }
}

fn gen_helper_methods(out: &mut String) {
    writeln!(out, "    // Helper methods for FFI marshalling").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    private static String readCString(MemorySegment ptr) {{").unwrap();
    writeln!(out, "        if (ptr == null || ptr.address() == 0) {{").unwrap();
    writeln!(out, "            return null;").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        return ptr.getUtf8String(0);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "    private static byte[] readBytes(MemorySegment ptr, long len) {{"
    )
    .unwrap();
    writeln!(out, "        if (ptr == null || ptr.address() == 0) {{").unwrap();
    writeln!(out, "            return null;").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        byte[] bytes = new byte[(int) len];").unwrap();
    writeln!(
        out,
        "        MemorySegment.copy(ptr, ValueLayout.JAVA_BYTE.byteSize() * 0, bytes, 0, (int) len);"
    )
    .unwrap();
    writeln!(out, "        return bytes;").unwrap();
    writeln!(out, "    }}").unwrap();
}
