use crate::type_map::python_type;
use skif_core::ir::{ApiSurface, EnumDef, FunctionDef, MethodDef, TypeDef};

pub fn gen_stubs(api: &ApiSurface) -> String {
    let mut lines = vec![
        "# This file is auto-generated by skif. DO NOT EDIT.".to_string(),
        "# Re-generate with: skif generate".to_string(),
        "".to_string(),
        "from typing import Any, Optional, Union, Dict, List, Tuple".to_string(),
        "".to_string(),
    ];

    // Generate type stubs
    for typ in &api.types {
        if typ.is_opaque {
            lines.push(gen_opaque_type_stub(typ));
            lines.push("".to_string());
        } else {
            lines.push(gen_type_stub(typ));
            lines.push("".to_string());
        }
    }

    // Generate enum stubs
    for enum_def in &api.enums {
        lines.push(gen_enum_stub(enum_def));
        lines.push("".to_string());
    }

    // Generate function stubs
    for func in &api.functions {
        lines.push(gen_function_stub(func));
        lines.push("".to_string());
    }

    lines.join("\n")
}

/// Generate a Python type stub for an opaque type (no fields, only methods).
fn gen_opaque_type_stub(typ: &TypeDef) -> String {
    let mut lines = vec![];

    if !typ.doc.is_empty() {
        lines.push(format!("class {}:", typ.name));
        lines.push(format!(r#"    """{}""""#, typ.doc));
    } else {
        lines.push(format!("class {}:", typ.name));
    }

    // Instance methods
    for method in &typ.methods {
        if !method.is_static {
            lines.push(gen_method_stub(method, false));
        }
    }

    // Static methods
    for method in &typ.methods {
        if method.is_static {
            lines.push(gen_method_stub(method, true));
        }
    }

    // If no methods at all, add pass
    if typ.methods.is_empty() {
        lines.push("    pass".to_string());
    }

    lines.join("\n")
}

/// Generate a Python type stub for a struct.
fn gen_type_stub(typ: &TypeDef) -> String {
    let mut lines = vec![];

    // Add docstring if present
    if !typ.doc.is_empty() {
        lines.push(format!("class {}:", typ.name));
        lines.push(format!(r#"    """{}""""#, typ.doc));
    } else {
        lines.push(format!("class {}:", typ.name));
    }

    // Add field type annotations
    for field in &typ.fields {
        let field_type = if field.optional {
            format!("{} | None", python_type(&field.ty))
        } else {
            python_type(&field.ty)
        };
        lines.push(format!("    {}: {}", field.name, field_type));
    }

    // Add __init__ signature
    lines.push(gen_type_init_stub(typ));

    // Add instance methods
    for method in &typ.methods {
        if !method.is_static {
            lines.push(gen_method_stub(method, false));
        }
    }

    // Add static methods
    for method in &typ.methods {
        if method.is_static {
            lines.push(gen_method_stub(method, true));
        }
    }

    lines.join("\n")
}

/// Generate __init__ signature stub for a struct.
fn gen_type_init_stub(typ: &TypeDef) -> String {
    let params: Vec<String> = typ
        .fields
        .iter()
        .map(|f| {
            let param_type = if f.optional {
                format!("{} | None", python_type(&f.ty))
            } else {
                python_type(&f.ty)
            };

            if f.optional {
                format!("{}: {} = None", f.name, param_type)
            } else {
                format!("{}: {}", f.name, param_type)
            }
        })
        .collect();

    format!("    def __init__(self, {}) -> None: ...", params.join(", "))
}

/// Generate a method stub.
fn gen_method_stub(method: &MethodDef, is_static: bool) -> String {
    let params: Vec<String> = method
        .params
        .iter()
        .map(|p| {
            let param_type = if p.optional {
                format!("{} | None", python_type(&p.ty))
            } else {
                python_type(&p.ty)
            };

            if p.optional {
                format!("{}: {} = None", p.name, param_type)
            } else {
                format!("{}: {}", p.name, param_type)
            }
        })
        .collect();

    let return_type = python_type(&method.return_type);
    let indent = "    ";

    if is_static {
        format!(
            "{}@staticmethod\n{}def {}({}) -> {}: ...",
            indent,
            indent,
            method.name,
            params.join(", "),
            return_type
        )
    } else {
        format!(
            "{}def {}(self, {}) -> {}: ...",
            indent,
            method.name,
            params.join(", "),
            return_type
        )
    }
}

/// Generate a Python enum stub.
fn gen_enum_stub(enum_def: &EnumDef) -> String {
    let mut lines = vec![];

    if !enum_def.doc.is_empty() {
        lines.push(format!("class {}:", enum_def.name));
        lines.push(format!(r#"    """{}""""#, enum_def.doc));
    } else {
        lines.push(format!("class {}:", enum_def.name));
    }

    for (idx, variant) in enum_def.variants.iter().enumerate() {
        lines.push(format!("    {}: int = {}", variant.name, idx));
    }

    lines.join("\n")
}

/// Generate a function stub.
fn gen_function_stub(func: &FunctionDef) -> String {
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| {
            let param_type = if p.optional {
                format!("{} | None", python_type(&p.ty))
            } else {
                python_type(&p.ty)
            };

            if p.optional {
                format!("{}: {} = None", p.name, param_type)
            } else {
                format!("{}: {}", p.name, param_type)
            }
        })
        .collect();

    let return_type = python_type(&func.return_type);

    if !func.doc.is_empty() {
        format!(
            "def {}({}) -> {}:\n    \"\"\"{}\"\"\"\n    ...",
            func.name,
            params.join(", "),
            return_type,
            func.doc
        )
    } else {
        format!("def {}({}) -> {}: ...", func.name, params.join(", "), return_type)
    }
}
