use crate::type_map::python_type;
use skif_core::ir::{ApiSurface, EnumDef, FunctionDef, MethodDef, TypeDef};

/// Convert a name to be safe for Python by escaping reserved keywords.
fn python_safe_name(name: &str) -> String {
    const PYTHON_KEYWORDS: &[&str] = &[
        "from", "import", "class", "def", "return", "yield", "pass", "break", "continue", "and", "or", "not", "is",
        "in", "if", "else", "elif", "for", "while", "with", "as", "try", "except", "finally", "raise", "del", "global",
        "nonlocal", "lambda", "assert", "type",
    ];
    if PYTHON_KEYWORDS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

pub fn gen_stubs(api: &ApiSurface) -> String {
    let mut lines = vec![
        "# This file is auto-generated by skif. DO NOT EDIT.".to_string(),
        "# Re-generate with: skif generate".to_string(),
        "".to_string(),
        "from typing import Any, Optional, Union, Dict, List, Tuple".to_string(),
        "".to_string(),
    ];

    // Generate type stubs
    for typ in &api.types {
        if typ.is_opaque {
            lines.push(gen_opaque_type_stub(typ));
            lines.push("".to_string());
        } else {
            lines.push(gen_type_stub(typ));
            lines.push("".to_string());
        }
    }

    // Generate enum stubs
    for enum_def in &api.enums {
        lines.push(gen_enum_stub(enum_def));
        lines.push("".to_string());
    }

    // Generate function stubs
    for func in &api.functions {
        lines.push(gen_function_stub(func));
        lines.push("".to_string());
    }

    lines.join("\n")
}

/// Generate a Python type stub for an opaque type (no fields, only methods).
fn gen_opaque_type_stub(typ: &TypeDef) -> String {
    let mut lines = vec![];

    if !typ.doc.is_empty() {
        lines.push(format!("class {}:", typ.name));
        lines.push(format!(r#"    """{}""""#, typ.doc));
    } else {
        lines.push(format!("class {}:", typ.name));
    }

    // Instance methods
    for method in &typ.methods {
        if !method.is_static {
            lines.push(gen_method_stub(method, false));
        }
    }

    // Static methods
    for method in &typ.methods {
        if method.is_static {
            lines.push(gen_method_stub(method, true));
        }
    }

    // If no methods at all, add pass
    if typ.methods.is_empty() {
        lines.push("    pass".to_string());
    }

    lines.join("\n")
}

/// Generate a Python type stub for a struct.
fn gen_type_stub(typ: &TypeDef) -> String {
    let mut lines = vec![];

    // Add docstring if present
    if !typ.doc.is_empty() {
        lines.push(format!("class {}:", typ.name));
        lines.push(format!(r#"    """{}""""#, typ.doc));
    } else {
        lines.push(format!("class {}:", typ.name));
    }

    // Add field type annotations
    for field in &typ.fields {
        let type_str = python_type(&field.ty);
        let field_type = if field.optional && !type_str.contains("| None") {
            format!("{} | None", type_str)
        } else {
            type_str
        };
        lines.push(format!("    {}: {}", field.name, field_type));
    }

    // Add __init__ signature
    lines.push(gen_type_init_stub(typ));

    // Add instance methods
    for method in &typ.methods {
        if !method.is_static {
            lines.push(gen_method_stub(method, false));
        }
    }

    // Add static methods
    for method in &typ.methods {
        if method.is_static {
            lines.push(gen_method_stub(method, true));
        }
    }

    lines.join("\n")
}

/// Generate __init__ signature stub for a struct.
fn gen_type_init_stub(typ: &TypeDef) -> String {
    // Partition fields into required (non-optional) and optional
    let (required, optional): (Vec<_>, Vec<_>) = typ.fields.iter().partition(|f| !f.optional);

    // Generate required params first, then optional params
    let mut params: Vec<String> = required
        .iter()
        .map(|f| {
            let param_type = python_type(&f.ty);
            format!("{}: {}", f.name, param_type)
        })
        .collect();

    params.extend(optional.iter().map(|f| {
        let type_str = python_type(&f.ty);
        let param_type = if !type_str.contains("| None") {
            format!("{} | None", type_str)
        } else {
            type_str
        };
        format!("{}: {} = None", f.name, param_type)
    }));

    format!("    def __init__(self, {}) -> None: ...", params.join(", "))
}

/// Generate a method stub.
fn gen_method_stub(method: &MethodDef, is_static: bool) -> String {
    // Partition params into required (non-optional) and optional
    let (required, optional): (Vec<_>, Vec<_>) = method.params.iter().partition(|p| !p.optional);

    // Generate required params first, then optional params
    let mut params: Vec<String> = required
        .iter()
        .map(|p| {
            let param_type = python_type(&p.ty);
            format!("{}: {}", p.name, param_type)
        })
        .collect();

    params.extend(optional.iter().map(|p| {
        let type_str = python_type(&p.ty);
        let param_type = if !type_str.contains("| None") {
            format!("{} | None", type_str)
        } else {
            type_str
        };
        format!("{}: {} = None", p.name, param_type)
    }));

    let return_type = python_type(&method.return_type);
    let indent = "    ";
    let safe_name = python_safe_name(&method.name);

    if is_static {
        if params.is_empty() {
            format!(
                "{}@staticmethod\n{}def {}() -> {}: ...",
                indent, indent, safe_name, return_type
            )
        } else {
            format!(
                "{}@staticmethod\n{}def {}({}) -> {}: ...",
                indent,
                indent,
                safe_name,
                params.join(", "),
                return_type
            )
        }
    } else {
        if params.is_empty() {
            format!("{}def {}(self) -> {}: ...", indent, safe_name, return_type)
        } else {
            format!(
                "{}def {}(self, {}) -> {}: ...",
                indent,
                safe_name,
                params.join(", "),
                return_type
            )
        }
    }
}

/// Generate a Python enum stub.
fn gen_enum_stub(enum_def: &EnumDef) -> String {
    let mut lines = vec![];

    if !enum_def.doc.is_empty() {
        lines.push(format!("class {}:", enum_def.name));
        lines.push(format!(r#"    """{}""""#, enum_def.doc));
    } else {
        lines.push(format!("class {}:", enum_def.name));
    }

    for (idx, variant) in enum_def.variants.iter().enumerate() {
        lines.push(format!("    {}: int = {}", variant.name, idx));
    }

    lines.join("\n")
}

/// Generate a function stub.
fn gen_function_stub(func: &FunctionDef) -> String {
    // Partition params into required (non-optional) and optional
    let (required, optional): (Vec<_>, Vec<_>) = func.params.iter().partition(|p| !p.optional);

    // Generate required params first, then optional params
    let mut params: Vec<String> = required
        .iter()
        .map(|p| {
            let param_type = python_type(&p.ty);
            format!("{}: {}", p.name, param_type)
        })
        .collect();

    params.extend(optional.iter().map(|p| {
        let type_str = python_type(&p.ty);
        let param_type = if !type_str.contains("| None") {
            format!("{} | None", type_str)
        } else {
            type_str
        };
        format!("{}: {} = None", p.name, param_type)
    }));

    let return_type = python_type(&func.return_type);
    let safe_name = python_safe_name(&func.name);

    if !func.doc.is_empty() {
        format!(
            "def {}({}) -> {}:\n    \"\"\"{}\"\"\"\n    ...",
            safe_name,
            params.join(", "),
            return_type,
            func.doc
        )
    } else {
        format!("def {}({}) -> {}: ...", safe_name, params.join(", "), return_type)
    }
}
