use crate::type_map::rbs_type;
use eisberg_core::ir::{ApiSurface, EnumDef, FunctionDef, MethodDef, TypeDef};

pub fn gen_stubs(api: &ApiSurface) -> String {
    let mut lines = vec![
        "# This file is auto-generated by eisberg. DO NOT EDIT.".to_string(),
        "# Re-generate with: eisberg generate".to_string(),
        "".to_string(),
    ];

    let module_name = get_module_name(&api.crate_name);
    lines.push(format!("module {}", module_name));
    lines.push("".to_string());

    // Generate type stubs
    for typ in &api.types {
        if typ.is_opaque {
            lines.push(gen_opaque_type_stub(typ));
            lines.push("".to_string());
        } else {
            lines.push(gen_type_stub(typ));
            lines.push("".to_string());
        }
    }

    // Generate enum stubs
    for enum_def in &api.enums {
        lines.push(gen_enum_stub(enum_def));
        lines.push("".to_string());
    }

    // Generate function stubs (module methods)
    for func in &api.functions {
        lines.push(gen_function_stub(func));
        lines.push("".to_string());
    }

    lines.push("end".to_string());

    lines.join("\n")
}

/// Convert crate name to PascalCase module name.
fn get_module_name(crate_name: &str) -> String {
    crate_name
        .split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// Generate a Ruby type stub for an opaque type (no fields, only methods).
fn gen_opaque_type_stub(typ: &TypeDef) -> String {
    let mut lines = vec![];

    lines.push(format!("  class {}", typ.name));

    if !typ.doc.is_empty() {
        lines.push(format!(r#"    # {}"#, typ.doc));
        lines.push("".to_string());
    }

    // Instance methods
    for method in &typ.methods {
        if !method.is_static {
            lines.push(gen_method_stub(method, false));
        }
    }

    // Static methods
    for method in &typ.methods {
        if method.is_static {
            lines.push(gen_method_stub(method, true));
        }
    }

    lines.push("  end".to_string());

    lines.join("\n")
}

/// Generate a Ruby type stub for a struct.
fn gen_type_stub(typ: &TypeDef) -> String {
    let mut lines = vec![];

    lines.push(format!("  class {}", typ.name));

    // Add docstring if present
    if !typ.doc.is_empty() {
        lines.push(format!(r#"    # {}"#, typ.doc));
        lines.push("".to_string());
    }

    // Add field attr_reader declarations
    for f in &typ.fields {
        let field_type = rbs_type(&f.ty);
        lines.push(format!(r#"    attr_reader {}: {}"#, f.name, field_type));
    }

    if !typ.fields.is_empty() {
        lines.push("".to_string());
    }

    // Add initialize method
    let init_params: Vec<String> = typ
        .fields
        .iter()
        .map(|f| {
            let field_type = rbs_type(&f.ty);
            if f.optional {
                format!("?{}: {}", f.name, field_type)
            } else {
                format!("{}: {}", f.name, field_type)
            }
        })
        .collect();

    lines.push(format!("    def initialize: ({}) -> void", init_params.join(", ")));

    // Add instance methods
    for method in &typ.methods {
        if !method.is_static {
            lines.push(gen_method_stub(method, false));
        }
    }

    // Add static methods
    for method in &typ.methods {
        if method.is_static {
            lines.push(gen_method_stub(method, true));
        }
    }

    lines.push("  end".to_string());

    lines.join("\n")
}

/// Generate a method stub.
fn gen_method_stub(method: &MethodDef, is_static: bool) -> String {
    let params: Vec<String> = method
        .params
        .iter()
        .map(|p| {
            let param_type = rbs_type(&p.ty);
            if p.optional {
                format!("?{}: {}", p.name, param_type)
            } else {
                format!("{}: {}", p.name, param_type)
            }
        })
        .collect();

    let return_type = rbs_type(&method.return_type);

    if is_static {
        format!("    def self.{}({}) -> {}", method.name, params.join(", "), return_type)
    } else {
        if params.is_empty() {
            format!("    def {}() -> {}", method.name, return_type)
        } else {
            format!("    def {}({}) -> {}", method.name, params.join(", "), return_type)
        }
    }
}

/// Generate a Ruby enum stub.
fn gen_enum_stub(enum_def: &EnumDef) -> String {
    let mut lines = vec![];

    lines.push(format!("  class {}", enum_def.name));

    // Add docstring if present
    if !enum_def.doc.is_empty() {
        lines.push(format!(r#"    # {}"#, enum_def.doc));
        lines.push("".to_string());
    }

    for variant in &enum_def.variants {
        lines.push(format!("    {}: Integer", variant.name));
    }

    lines.push("  end".to_string());

    lines.join("\n")
}

/// Generate a function stub (module method).
fn gen_function_stub(func: &FunctionDef) -> String {
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| {
            let param_type = rbs_type(&p.ty);
            if p.optional {
                format!("?{}: {}", p.name, param_type)
            } else {
                format!("{}: {}", p.name, param_type)
            }
        })
        .collect();

    let return_type = rbs_type(&func.return_type);

    if params.is_empty() {
        format!("  def self.{}() -> {}", func.name, return_type)
    } else {
        format!("  def self.{}({}) -> {}", func.name, params.join(", "), return_type)
    }
}
